- name: Running two tier app
  hosts: app
  become: true 
  tasks:
    - name: cloning app
      git:
        repo: https://github.com/arpanelfranklin/Tea-app.git
    - name: docker compose
      docker_compose:
        project_src: ./Tea-app/
        files: "docker-compose.yml"
        state: present
