
- name: Running two tier app
  hosts: app
  become: true 
  vars:
    project_path: "/home/{{ ansible_user_id }}/Tea-app"
  tasks:
    - name: cloning app
      git:
        repo: https://github.com/arpanelfranklin/Tea-app.git
        dest: "{{ project_path }}"
        force: yes
    - name: docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        files: 
          - "docker-compose.yml"
        state: present
